# Generated by Django 4.2.19 on 2025-02-20 17:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0010_alter_quiz_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 23, 36, 46, 569336)),
        ),
    ]
