# Generated by Django 4.2.19 on 2025-02-21 10:40

from django.conf import settings
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0014_alter_quiz_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='liked_by',
            field=models.ManyToManyField(blank=True, related_name='liked_quizzes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='following', to='quizzes.userprofile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='topics',
            field=models.ManyToManyField(blank=True, to='quizzes.topic'),
        ),
    ]
