# Generated by Django 4.2.19 on 2025-02-21 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizzes', '0016_userprofile_address_userprofile_email_public_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='explanation',
            field=models.TextField(blank=True, help_text='Provide an explanation for the correct answer', null=True),
        ),
    ]
