# Generated by Django 4.2.19 on 2025-02-25 18:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizzes', '0022_alter_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='target_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='targeted_quizzes', to=settings.AUTH_USER_MODEL),
        ),
    ]
